name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: 'Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: 'Bugs Fixes'
    labels:
      - 'bug'
      - 'bugfix'
      - 'fix'
  - title: 'Documentation'
    labels:
      - 'documentation'
  - title: 'Configuration'
    labels:
      - 'config'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ## Changes

  $CHANGES