changelog:
  categories:
    - title: New features
      labels:
        - enhancement
    - title: Fixes
      labels:
        - bug
        - fix
    - title: Other Changes
      labels:
        - "*"