variables:
  DOCKER_DRIVER: overlay2
  DOCKER_CACHE_IMAGE: $CI_REGISTRY_IMAGE:latest
  DOCKER_IMAGE: $CI_REGISTRY_IMAGE:$CI_PIPELINE_IID
  GIT_DEPTH: 1

stages:
  - pre_build
  - build
  - release

docker:lint:
  image: hadolint/hadolint:v1.18.0-6-ga0d655d-debian
  stage: pre_build
  script:
    - hadolint Dockerfile

build:
  stage: build
  image: docker:19
  services:
    - docker:19-dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker pull $DOCKER_CACHE_IMAGE || true
    - docker build --cache-from $DOCKER_CACHE_IMAGE -t $DOCKER_IMAGE -t $DOCKER_CACHE_IMAGE .
    - docker push $DOCKER_CACHE_IMAGE
    - docker run -v $(pwd)/bin:/mnt/bin $DOCKER_IMAGE cp bin/deployer /mnt/bin
    - echo "APP_VERSION=$(cat VERSION)" >> app.env
  artifacts:
    reports:
      dotenv: app.env
    paths:
      - bin/deployer

release:bin:
  image: alpine:3
  stage: release
  artifacts:
    name: "deployer-v$APP_VERSION"
    paths:
      - bin/deployer
