linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - unconvert
    - wsl
    - grouper
    - godot
    - gocritic
    - whitespace
    - usestdlibvars
    - prealloc
    - nilnil
    - nilerr
    - gochecknoinits
    - dupl
