name: Build

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build
        id: build
        run: |
          VERSION=$(cat VERSION)
          GOOS=linux
          GO111MODULE=on
          CGO_ENABLED=0
          go build -a -installsuffix cgo -ldflags="-X 'deployer/internal/core.Version=v${VERSION}'" -o bin/deployer deployer/cmd/server
          echo "::set-output name=VERSION::$VERSION"

      - name: Test
        run: go test -v ./...

      - name: Upload executable
        uses: actions/upload-artifact@v2
        with:
          name: deployer_${{ steps.build.outputs.VERSION }}
          path: bin/deployer

