name: Build

on: [ pull_request, push ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - uses: actions/checkout@v3

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.49.0

      - name: Build
        id: build
        run: go build deployer/cmd/server

      - name: Test
        run: go test -v ./...
