name: "Create draft release"

on: push

jobs:
  update_draft_release:
    runs-on: ubuntu-20.04
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}