name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Build
        id: build
        run: |
          VERSION=$(cat VERSION)
          GOOS=linux
          GO111MODULE=on
          CGO_ENABLED=0
          go build -a -installsuffix cgo -ldflags="-X 'deployer/internal/config.Version=v${VERSION}'" -o bin/deployer deployer/cmd/server
          echo "::set-output name=VERSION::$VERSION"

      - name: Test
        run: go test -v ./...

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: bin/deployer
          generate_release_notes: true
